<a href="https://colab.research.google.com/github/smc219/CodeReview/blob/master/tensor/2%EB%B6%80_1%EA%B3%BC_AI%EB%A5%BC_%EC%9C%84%ED%95%9C_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter2-1. TensorFlow 기초 - AI를 위한 NumPy

## [1] Import NumPy

> ### Import NumPy

In [1]:
import numpy as np

print("NumPy Version : {}".format(np.__version__))

NumPy Version : 1.17.4


## [2] Python vs NumPy

> ### Python

In [0]:
L = range(1000)

노트북에는 %기호 뒤에 붙여쓸 수 있는 특수 커맨드, 속칭 매직커맨드가 있다. timeit역시 시간을 측정하기 위해서 사용되는 커맨드이다.

In [4]:
%timeit [i**2 for i in L]

1000 loops, best of 3: 220 µs per loop


>### NumPy

arange. range의 결과물을 array로 만들어준다.

In [0]:
a = np.arange(1000)
b = np.arange(100, 120, 4)

print(b.ndim) # 1차원 배열이 만들어질테니 depth는 1로 나올 것
print(b)
print(a)
print(type(a))

1
[100 104 108 112 116]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 24

In [0]:
%timeit a**2

The slowest run took 5919.36 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.26 µs per loop


위의 결과를 보면 연산처리속도 차이가 크게 남. 메모리에 물리적으로 액세스가 가능하니까. 캐시의 효과도 볼 수 있는 것.

## [3] np.ndarray 생성 : np.array()

arange를 가지고 만든 결과물 -> numpy의 ndarray.

numpy는 배열 기반으로 만듦. 그래서 이 ndarray 타입이 굉장히 중요하다.

1차원 구조인 것을 보여주기 위해서 (5, )라는 식으로 표현.

리스트의 경우에는 요소들간 타입이 달라도 됨. 그러나 numpy의 어레이는 어쨌건 array, 모든 요소의 타입이 다 같아야한다. 

dtype이라는 요소. 요소들이 어떤 속성인가를 알려준다. 나머지 것들은 크게 중요하지 않기때문에 현재는 생략한다.

> ### 1-D Array

array-like한 것을 넣어주면 된다. list, list of tuple, tuple, tuple tuple, tuples of list and ndarrays

In [0]:
a = np.array([0, 1, 2, 3])
print(a)
print(a.ndim)
print(a.shape)
print(len(a))
b = np.array([ \
              [ \
               [10, 20, 30], \
               [40, 50, 60] \
              ], \
              [
                [20, 30, 40], \
               [10, 15, 30]\
              ],
              [ \
               [10, 20, 30], \
               [40, 50, 60] \
              ], \
              [
                [22, 33, 45], \
               [12, 16, 32]\
              ]
              

])
print(b.ndim)
print(b.transpose(2, 0, 1)) #  즉 두개뿐인 2차원 배열의 내용들이 밖을 묶는 요소들이 된다. 0번째 1번째 그리고 그 안에 두개의 요소가 있고


[0 1 2 3]
1
(4,)
4
3
[[[10 40]
  [20 10]]

 [[20 50]
  [30 15]]

 [[30 60]
  [40 30]]]


> ### 2-D Array

배열을 만들기 어려운 경우에 어떻게 될까?
```python
b = np.array([0, 1, 2, 3], [3. 4, 5])
```
이때 b는 어떤 식으로 찍힐까?

In [0]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)
print(b.ndim)
print(b.shape)
print(len(b))

[list([0, 1, 2, 3]) list([3, 4, 5])]
1
(2,)
2


> ### 3-D Array

In [0]:
c = np.array([[[1], [2]], [[3], [4]]])
print(c)
print(c.ndim)
print(c.shape)
print(len(c))

[[[1]
  [2]]

 [[3]
  [4]]]
3
(2, 2, 1)
2


## [4] np.ndarray 생성하는 다른 함수들

> ### np.arange()

파이썬의 range와 동일하다고 생각하면 됨.

In [0]:
a = np.arange(10)
print(a)

b = np.arange(1, 9, 2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


>### np.linspace()

처음값과 끝값을 정해주면 linear한 어떤 값의 array를 만들어준다.

0, 1사이에 6개의 스텝이 있는 배열을 만들어준다. 

In [0]:
c = np.linspace(0, 1, 6)
print(c)

d = np.linspace(0, 1, 5, endpoint=False)
print(d)

e = np.linspace(0, 100, 11)
print(e)

[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


>### np.ones(), np.zeros(), np.eye()

eyes는 항등 행렬을 만들어준다. 정사각형 행렬에서만 만들어지기 때문에 숫자 * 숫자짜리의 행렬을 만들어 준다.

In [0]:
a = np.ones((3, 3))
print(a)

b = np.zeros((2, 2))
print(b)

c = np.eye(3)
print(c)

>### np.ones_like(), np.zeros_like(), np.empty_like()

동일한 shape인데 0만있는 shape, 1만 있는 shape, 

In [0]:
a = [1,2,3,4]
a_like = np.ones_like(a)
print(a_like)

b = [[1,2,3],[4,5,6]]
b_like = np.zeros_like(b)
print(b_like)

c = [[1,2, 3],[3,4, 5]]
c_like = np.empty_like(c)
print(c_like)

[1 1 1 1]
[[1 2 3]
 [3 4 5]]


## [5] Basic Data Type

dtype

보통 float64가 가장 기본적인 형태가 된다.

사실 문자열 타입과 같은 것들은 이번 수업때는 사용하지 않을 것으로 보임.

실제로 사용할때는 np.자료형, (np.int8, np.int16)으로 사용한다.

>### np.ndarray.dtype

In [0]:
a = np.array([1, 2, 3])
print(a.dtype)

b = np.array([1., 2., 2135224534645756.142222222222222222222222222222233333333333142142124124115124321531242153123151])
print(b.dtype)

c = np.array([1+2j, 3+4j, 5+6*1j])
print(c.dtype)

d = np.array([True, False, False, True])
print(d.dtype)

int64
float64
complex128
bool


>### array 생성 시 dtype 지정

우리가 원하는 타입을 지정해서 만드는 것이 가능하다.

In [0]:
e = np.array([1, 2, 3], dtype=float)
print(e.dtype)

f = np.array([1., 2., 3., 4], dtype=int)
print(f.dtype)

float64
int64


## [6] Indexing & Slicing

Indexing과 Slicing은 원본의 VIEW

예를 들어서 ```[1,2,3,4,5]```
라고 해보자.

즉 뭔가가 새로 만들어지는게 아니라 같은 녀석을 바라본다는 것.
이런 것을 VIEW라고 한다. 

인덱싱도 그러하고, 슬라이싱도 슬라이싱한 결과에 새로운 오브젝트가 만들어지는게 아니라 VIEW의 관점으로 만들어진다.



> ### 기본 Indexing 방법

In [0]:
a = np.arange(10)
print(a)
print(a[0])
print(a[2])
print(a[-1])

[0 1 2 3 4 5 6 7 8 9]
0
2
9


>### Multidimensional array의 Indexing

```a[2, 1] = 10```

이걸바꾸면 어떻게 바뀔까?

```
1 0 0 
1 1 0
0 10 1 의 형태로 출력이 될 것,
```

#복습

여기서 확인할 점은 슬라이싱한 내용들은 기본적으로 VIEW라는 점.

In [5]:
a = np.eye(3)

print(a,'\n')
print(a[1, 1],'\n')

a[2, 1] = 10 # VIEW이기 때문에 값이 바뀌는 것을 확인할 수 있다
print(a[2, 1],'\n')   # third line, second column

print(a,'\n')
print(a[1],'\n')



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

1.0 

10.0 

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. 10.  1.]] 

[0. 1. 0.] 



>### Slicing

In [0]:
a = np.arange(10)

print(a,'\n')

print(a[2:9:3],'\n') # [start:end:step]

print('====================')
print(a[-1:3:-2],'\n')
print(a[:4],'\n')

print(a[1:3],'\n')

print(a[::2],'\n')

print(a[3:],'\n')

[0 1 2 3 4 5 6 7 8 9] 

[2 5 8] 

[9 7 5] 

[0 1 2 3] 

[1 2] 

[0 2 4 6 8] 

[3 4 5 6 7 8 9] 



```
b[::-1]
```
이 뒤집혀서 대입된다.
사이즈가 다르면 Broadcating을 할 수 없다는 얘기가 나오며 안됨 

In [0]:
a = np.arange(10)
print(a,'\n')
a[5:] = 10 # broadcast가 가능해서 되는걸까?
print(a,'\n')

b = np.arange(5)
print(b,'\n')
a[5:] = b[::-1]
print(a,'\n')

[0 1 2 3 4 5 6 7 8 9] 

[ 0  1  2  3  4 10 10 10 10 10] 

[0 1 2 3 4] 

[0 1 2 3 4 4 3 2 1 0] 



## [7] Copies and views

>### 'b'의 정체?

In [0]:
a = np.arange(10)
print(a)
b = a[::2]
print(b)

print(np.may_share_memory(a, b))

b[0] = 12
print(b.base) # 해당 어레이 객체가 뷰일때 그 원본이 누구인지를 알려준다.
print(b)
print(a)
#stride. 어떤 데이터를 몇개를 건너뛰면서 볼 것인가.
print(b.strides) # 바이트 단위로 나온다. int64만들어졌을거니까, 8바이트가 두번 건너뛰었을 것.

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True
[12  1  2  3  4  5  6  7  8  9]
[12  2  4  6  8]
[12  1  2  3  4  5  6  7  8  9]
(16,)


>### 강제 Copy 만들기

#복습

그래서 카피를 만들고 싶다면 copy함수를 이용해야 한다. 

In [0]:
a = np.arange(10)
c = a[::2].copy() # 말 그대로 값을 복사해서 새로운 값을 만드는 것.
print(a)
print(c)

c[0] = 12
print(a)

print(np.may_share_memory(a, c))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
False


## [8] Elementwise operation

> ### Scalar value와 Array 사이의  연산

Scala value. 그냥 일단은 요소가 아니라 값 하나, 크기 값 정도로만 생각하길 바람

대부분의 연산 -> Elementwise로 하게 된다.

어떤 배열들의내용을 연산할때 배열의 요소들끼리 연산을 하는 것이다. 

#복습

elementwise로 계산한다는 것은 broadcasting이 일어나고, 그리고 나서 계산한다는 것

아래의 코드에서는 1이 차원 확장이 먼저 되고, 그 다음 같은 열이 되도록 스트레치가 일어난다

In [6]:
a = np.array([1, 2, 3, 4])
print(a + 1)
print(2 ** a)

[2 3 4 5]
[ 2  4  8 16]


>### Array와 Array 사이의 연산

In [0]:
b = np.ones(4) + 1

print(a - b)
print(a * b)

j = np.arange(5)
print(2**(j + 1) - j)


>### c * c => Matrix Multiplication?

그냥 elementwise 연산이 이뤄진 것을 확인할 수 있다.

#복습

기본적으로 발생하는 연산은 elementwise 연산이다. 그래서 행렬간 연산이 필요할 때는 matmul따위의 연산을 해주어야 한다.

In [8]:
c = np.ones((3, 3))
d = np.matmul(c, c)
print(c * c * 3)
print(d)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


>### Matrix Multiplication : np.dot

아래 메소드를 사용해야 행렬의 곱을 수행한다.

실제로는 dot product 연산을 할 때 사용하는 연산이다.

In [0]:
mat_mul = np.dot(c,c)
print(mat_mul)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


>### Element-wise 비교

하나하나씩 적용돼서 나옴(element wise)

# 복습

이 부분이 개념이 잘 안잡혀 있는데 ndarray의 경우에는 변수를 넣어주면 개별 계산이 가능하다는 사실을 잊지 말 것!

np.where의 경우에도 이와 유사한 방식으로 사용됐던 것 같음ㅇㅇ

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.where(a == b)
print(a == b)
print(a > b)

[False  True False  True]
[False False  True False]


>### Element-wise 논리연산

In [0]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

print(np.logical_or(a, b))
print(a|b)

print(np.logical_and(a, b))
print(a&b)

[ True  True  True False]
[ True  True  True False]
[ True False False False]
[ True False False False]


>### Element-wise 연산에서 operand들의 shape mismatche

#복습

왜 stretch가 되지 않을까?

>The new elements in b, as shown in Figure 1, are simply copies of the original scalar. The stretching analogy is only conceptual. numpy is smart enough to use the original scalar value without actually making copies so that broadcasting operations are as memory and computationally efficient as possible.

상단의 내용에서 확인할 수 있는 것처럼 numpy는 값을 "복사"해서 stretch해준다.

> In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.

하지만 numpy manual이 설명하고 있는것처럼 만약 shape이 다르거나, 또는 값이 하나가 아닌 상황이라면 당연히 될리가 없다.
아래의 예제는 shape (4, ) 꼴인 a와 [1, 2]는 shape도 다를 뿐더러 [1, 2]는 값이 하나도 아니기 때문에 broadcasting이 일어나지 않는다.



In [0]:
a = np.arange(4)
a + np.array([1, 2])  # Error가 뜨는 이유는 stretch가 되지 않기 때문. 

ValueError: ignored

## [9] Dimension reduction 연산

>### np.sum(), np.ndarray.sum()

In [0]:
x = np.array([1, 2, 3, 4])

print(np.sum(x))

print(x.sum())

10
10


>### 특정 축을 기준으로 합계 구하기

#복습

헷갈리기 쉬운 지점은 axis=0쪽이 아래쪽이고 1이 오른쪽이라는 

In [0]:
x = np.array([[1, 1], [2, 2]])

print(x.sum(axis=0))

print(x.sum(axis=1))

[3 3]
[2 4]


>### np.ndarray.min(), np.ndarray.max(), np.ndarray.argmin(), np.ndarray.argmax() 

In [0]:
x = np.array([1, 3, 2])

print(x.min())
print(x.max())

print(x.argmin()) #역시나 자주 쓰임
print(x.argmax())

1
3
0
1


In [0]:
x = np.array([[9,2,10,6,1],[5,7,3,4,8]])

print(x.argmin(axis=0))
print(x.argmax(axis=1))

[1 0 1 1 0]
[2 4]


>### np.all(), np.any()

In [0]:
print(np.all([True, True, False]))
print(np.any([True, True, False]))

False
True


>### 통계 관련

In [0]:
x = np.array([1, 2, 199])
y = np.array([[1, 2, 3], [5, 6, 1]])

print(x.mean())

print(np.median(x))
print(np.median(y, axis=-1))

print(x.std())

67.33333333333333
2.0
[2. 5.]
93.10328792380119


## [10] Broadcasting

shape이 서로 다를때 어떤 식으로 계산할 것인가.

loop을 사용하지 않고 연산하는 것 -> vectorizing이라고 한다.

차원의 확장에 대한 개념과 stretch에 대한 개념을 이해해야한다.

하나의 스칼라값을 1차배열로도, 2차배열로도 만들 수 있다. 그러나 무작정 차원을 늘리는 것이 가능한 것은 아님.

가장 높은 차원쪽에서 차원을 확장시키는 방법과 가장 깊숙한 곳에서 차원을 확장시키는 방법이 있다.

요소 가장 밖을 괄호하거나, 요소 하나하나를 괄호하거나.

확장된 차원의 요소의 개수는 어쨌건 하나가 된다.

**stretching**

```[[1, 2]]```

이런 배열이 하나 있다고 하자.

이걸

```
[[1, 2],
[1, 2]]
```
이렇게 늘리고 싶다면? 이런 식으로 배열의 요소의 개수를 복제해서 늘리는 것을 stretch라고 한다.

요소가 두개라면 stretch가 가능할까?

```
[[1, 2],
 [3. 4]]

```
이런 형태라면? 
stretch는 요소의 개수가 하나였던 애를 대상으로는 늘릴 수 있다.
그 요소를 여러개 만드는 것이다.

결국 broadcasting은 차원을 늘리는 일과 stretching을 적용해서 두개의 operand가 같은 사이즈가 되도록 할 것이다.



>### 결과 출력용 함수

In [0]:
def Print_ABC(a, b, c):
    print("{}, a.shape = {}".format(a, a.shape))
    print("{}, b.shape = {}".format(b, b.shape))
    print("{}, c.shape = {}".format(c, c.shape))    

>### array + scalar

브로드캐스팅의 관점에서 얘기할 수 있다.

아래의 것은 b가 먼저 [2]로 차원의 확장이 일어나고, stretch가 일어나는 것이다.

> 결국 차원이 다르면 차원을 먼저 일치시켜주고 그 후에 개수를 일치시켜주는 듯


In [0]:
a = np.array([1, 2, 3])
b = 2
c = a + b

Print_ABC(a, np.array(b), c)

[1 2 3], a.shape = (3,)
2, b.shape = ()
[3 4 5], c.shape = (3,)


>### array + array ex1

b를 stretch해서 요소 두개짜리로 바꿔서 처리하는 것.

# 복습

이런 경우에는 어떻게 처리될까? 

b의 shape가 지금 a의 행 중 하나와 동일하기 떄문에 이 경우에는 broadcasting이 가능한 상황이다.
그래서 이에 먼저 일단 차원확장이 우선적으로 일어나고 그 후 값이 stretch된다.


In [0]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([1, 2, 3])
c = a + b
# 예를 들어서 한반의 구성원은 2명, 다른 반의 구성원은 한명이라고 하고 (그게 a, b라고 해보자.) 이 두 반의 점수를 평균 내야한다면?
# 사실 sum으로 처리하겠지...

print(np.sum(a) + np.sum(b))

Print_ABC(a, b, c)

ddddddd
27
[[1 2 3]
 [4 5 6]], a.shape = (2, 3)
[1 2 3], b.shape = (3,)
[[2 4 6]
 [5 7 9]], c.shape = (2, 3)


>### array + array ex2

일단 차원을 한번 확장. (1, 4)로 만들고
그걸 stretch해서 2행짜리로 만드는 것.

그리고 b는 열의 사이즈를 4로 스트레칭하는 것. 


In [0]:
a = np.array([1, 2, 3, 4])  
b = np.array([[1], [2]])
c = a + b

Print_ABC(a, b, c)

[1 2 3 4], a.shape = (4,)
[[1]
 [2]], b.shape = (2, 1)
[[2 3 4 5]
 [3 4 5 6]], c.shape = (2, 4)


>### array + array ex3



> 쉽게 생각해서 앞 뒤를 같은 값으로 맞춰준다고 생각하면 될듯.
이 때 앞 뒤가 같은 값으로 맞춰질 수 있는지를 판별해주고, 판별 결과 가능하다고 하면 진행





In [0]:
a = np.array([[1], [2], [3], [4]]) #shape가 (4, 1)
b = np.array([1, 2, 3]) # shape가 (3, ) -> 1행이니까 4행으로 먼저 맞춰준다. 
c = a + b

Print_ABC(a, b, c)

[[1]
 [2]
 [3]
 [4]], a.shape = (4, 1)
[1 2 3], b.shape = (3,)
[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]], c.shape = (4, 3)


## [11] Array Manipulation

데이터들을 쭉 평탄화시키고 싶다면? 즉 행 하나로 늘여뜨리고 싶다면 이를 Flatten하게 만든다고 한다.

메모리 상의 변화는 없음. 그냥 shape만 바뀐다.

아래의 함수 사용할..일...없음...

flattening할 일은 많은데, 실제로 저 함수를 굳이 사용하느냐, 하면 아니라고...

>### Flattening : np.ndarry.ravel()

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.ravel())

>### Reshaping : np.ndarray.reshape
#### ndarray.reshape may return a view (cf help(np.reshape))), or copy

2행 3열짜리 배열에서 a배열을 reshape해서 사용하겠다는 것.

6행 1열짜리로 바꾼다고 생각해보자. 메모리의 구조는 바뀌지 않으면서 shape만 바꾸는 것. 

reshape은 그때 그때 결과가 다르다고...

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a.reshape((6, 1))
print(b)

c = a.reshape((3, 2))
print(c)

print(a.reshape((-1,))) # -1을 사용했다 => 다른 차원의 사이즈와 맞춰서 알아서 정하라는 것. 그래서 flatten할 때도 이걸 사용...

[1 2 3 4 5 6 1 3 4]


In [0]:
a.reshape((2, -1))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 3, 4]])

>### Transpose

a는 transpose한다고 바뀌진 않음

보통 transpose를 사용하는 이유?

어떤 데이터를 분류하고 싶은데 이미지 데이터를 분류하고 싶다면...?

행, 열, 채널 순으로 짜인 것을 채널, 행, 열 순으로 받고 싶다면?

다차로 가게 되면 transpose를 할 때, n번 축을 기존의 몇번 축으로 대체할 것인가를 기정해서 transpose시킬 수 있다. 

axis(대체하고 싶은 축 번호, 번호, 번호...) 꼴로 가능

보통 딥러닝 개발자들은 암묵적으로 4차배열의 이미지를 받길 바람.

(Batch size , 채널, 행, 열)

Batch Size? 그림 데이터여러개 줄 때 그림의 개수가 들어가게 되는 것.

이런 식으로 데이터를 줄 때 그림이 하나면 앞쪽으로 하나 늘리고 4차로 만들어서 처리함.

In [0]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])


print(a)
print(a.transpose()) # 2차일때는 별도의 매개변수 줄 것이 없다. 0<=>1 뒤집기 외에 선택지가 없기 때문
print(a.T)
print(a)
print(b.shape)

NameError: ignored

> ### Dimension shuffling

In [0]:
a = np.arange(4*3*2).reshape((4, 3, 2))+1

print(a[0, 2, 1])

b = a.transpose((1, 2, 0))
print(b.shape)
print(b[2, 1, 0])